name: Deploy IaC (Terraform)
run-name: ${{ github.actor }} is starting the execution of gitops pipeline "Deploy IaC (Terraform)" with GitHub Actions
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
  TF_VAR_apigateway_integration_uri: ${{ secrets.TF_VAR_APIGATEWAY_INTEGRATION_URI }}
  TF_VAR_apigateway_jwt_configuration_audience: ${{ secrets.TF_VAR_APIGATEWAY_JWT_CONFIGURATION_AUDIENCE }}
  TF_VAR_apigateway_jwt_configuration_issuer: ${{ secrets.TF_VAR_APIGATEWAY_JWT_CONFIGURATION_ISSUER }}
jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Execute Terraform
        working-directory: ./pro
        run: sh deploy-architecture.sh
