name: Deploy IaC (Terraform)
run-name: ${{ github.actor }} is starting the execution of gitops pipeline "Deploy IaC (Terraform)" with GitHub Actions
on:
  pull_request:
    branches: [ "develop", "master" ]
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Execute Terraform
        working-directory: ./pro
        run: sh deploy-architecture.sh
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
