name: Deploy IaC (Terraform)
run-name: ${{ github.actor }} is starting the execution of gitops pipeline "Deploy IaC (Terraform)" with GitHub Actions
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Execute Terraform
        working-directory: ./pro
        run: sh deploy-architecture.sh
      - name: Send Message to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "The execution of gitops pipeline 'Deploy IaC (Terraform)' with GitHub Actions have finished"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
