name: Deploy IaC (Terraform)
run-name: ${{ github.actor }} is starting the execution of gitops pipeline "Deploy IaC (Terraform)" with GitHub Actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Execute Terraform
        run: sh pro/deploy-architecture.sh
